project:
  type: website
    

lang: de-CH

website:
  title: "Vegetation der Schweiz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: database.qmd
        text: "Vegetationsdatenbank"
      - href: grasland.qmd
        text: "Grasland"
      - href: zeitreihen.qmd
        text: "Zeitreihen"

metadata:
  keywords: Vegetation, Schweiz, Europa, Grasland, Wald, Wiederholungsaufnahme, Vegetations-Datenbank, Vegetationsaufnahme, Vegetationsveränderung, Biodiversität, ökologischer Zeigerwert, historische Daten, Quadratfuss-Projekt, Makroökologie, globaler Wandel, Zeitreihe
  description-meta: Das Informationsportal vegetation.ch enthält interaktive Dashboards zur nationalen Vegetationsdatenbank, Grasslanddiversität und Zeitreihen von Vegetation
  pagetitle: Pflanzendiversität und Vegetation der Schweiz 


format:
  html:
    theme: minty
    css: styles.css
    toc: true
    email-obfuscation: javascript
    # pagetitle: Pflanzendiversität und Vegetation der Schweiz
    # description-meta: Das Informationsportal vegetation.ch enthält interaktive Dashboards zur nationalen Vegetationsdatenbank, Grasslanddiversität und Zeitreihen von Vegetation
    pagetitle: Plant diversity and vegetation of Switzerland
    description-meta: The information portal vegetation.ch contains interactive dashboards on the national vegetation database, grassland diversity and vegetation resurveys



