project:
  type: website

website:
  title: "Vegetation der Schweiz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Biodiverstiy-Explorer.qmd
        text: "Biodiversity-Explorer"
      - href: resurvey.qmd
        text: "Zeitreihen"

lang: de-CH

format:
  html:
    theme: minty
    css: styles.css
    toc: true



