project:
  type: website
  post-render: echo "vegetation.ch" > _site/CNAME

lang: de-CH

website:
  title: "Vegetation der Schweiz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: grasland.qmd
        text: "Grasland"
      - href: zeitreihen.qmd
        text: "Zeitreihen"
      - href: database.qmd
        text: "Vegetationsdatenbank"


format:
  html:
    theme: minty
    css: styles.css
    toc: true
    email-obfuscation: javascript



